//AUTENTICACIÓN
export const POST_LOGIN = "POST_LOGIN"; /* ACCION PARA INICIAR SESION */
export const LOGOUT = "LOGOUT"; /* ACCION PARA CERRAR SESION */
export const POST_REGISTER = "POST_REGISTER"; /* ACCION PARA REGISTRO DE UN USUARIO */
export const GET_USERS = "GET_USERS"; /* ACCION PARA DATOS DE USUARIOS */

//PAGO DE POLIZAS
export const GET_POLIZAS = "GET_POLIZAS"; /* ACCION OBTENER DATOS DE POLIZAS */
export const CREATE_POLIZA = "CREATE_POLIZA"; /* ACCION PARA CREAR POLIZA */
export const UPDATE_POLIZA = "UPDATE_POLIZA"; /* ACCION PARA EDITAR POLIZA */
export const DELETE_POLIZA = "DELETE_POLIZA"; /* ACCION PARA ELIMINAR POLIZA */

//CLIENTES
export const GET_CLIENTES = "GET_CLIENTES"; /* ACCION PARA DATOS DE LOS CLIENTES */

//VALORES DE POLIZAS
export const GET_VALOR_POLIZA = "GET_VALOR_POLIZA"; /* ACCION PARA LA INFORMACION DE LOS VALORES DE POLIZAS */
export const GET_TIPO_POLIZAS = "GET_TIPO_POLIZAS";
export const GET_TIPO_EMPRESA = "GET_TIPO_EMPRESA";
export const CREATE_VALOR_POLIZA = "CREATE_VALOR_POLIZA"; /* ACCION PARA CREAR VALOR DE POLIZA */
export const UPDATE_VALOR_POLIZA = "UPDATE_VALOR_POLIZA"; /* ACCION PARA EDITAR VALOR DE POLIZA */
export const DELETE_VALOR_POLIZA = "DELETE_VALOR_POLIZA"; /* ACCION PARA ELIMINAR VALOR DE POLIZA */

//CUOTAS
export const GET_CUOTAS = "GET_VALOR_POLIZA"; /* ACCION PARA LA INFORMACION DE LAS CUOTAS */
export const CREATE_CUOTA = "CREATE_VALOR_POLIZA"; /* ACCION PARA CREAR CUOTA */
export const UPDATE_CUOTA = "UPDATE_CUOTA";  /* ACCION PARA EDITAR CUOTA */
export const DELETE_CUOTA = "DELETE_CUOTA";  /* ACCION PARA ELIMINAR CUOTA */


//CUADRE DE CAJA
export const GET_PAGOS = "GET_PAGOS"; /* ACCION PARA VER LOS PAGOS */
export const CREATE_PAGO = "CREATE_PAGO"; /* ACCION PARA CREAR PAGO */
export const UPDATE_PAGO = "UPDATE_PAGO"; /* ACCION PARA EDITAR PAGO */
export const DELETE_PAGO = "DELETE_PAGO"; /* ACCION PARA ELIMINAR PAGO */

//VEHICULOS
export const GET_VEHICULOS = "GET_VEHICULOS"; /* ACCION PARA OBTENER LOS DATOS DE LOS VEHICULOS */
export const CREATE_VEHICULO = "CREATE_VEHICULO"; /* ACCION PARA CREAR VEHICULOS */
export const UPDATE_VEHICULO = "UPDATE_VEHICULO"; /* ACCION PARA ACTUALIZAR VEHICULOS */
export const DELETE_VEHICULO = "DELETE_VEHICULO"; /* ACCION PARA ELIMINAR VEHICULOS */


//ELIMINACION EN CASCADA
export const GET_DETAIL_POLICYS = "GET_DETAIL_POLICYS"; /* ACCIÓN PARA VER DETALLES DE POLIZAS ELIMINADAS */