export const POST_LOGIN = "POST_LOGIN"; /* ACCION PARA INICIAR SESION */
export const LOGOUT = "LOGOUT"; /* ACCION PARA CERRAR SESION */
export const POST_REGISTER = "POST_REGISTER"; /* ACCION PARA REGISTRO DE UN USUARIO */
export const GET_POLIZAS = "GET_POLIZAS"; /* ACCION OBTENER DATOS DE POLIZAS */
export const GET_USERS = "GET_USERS"; /* ACCION PARA DATOS DE USUARIOS */
export const GET_CLIENTES = "GET_CLIENTES";/* ACCION PARA DATOS DE LOS CLIENTES */
export const GET_CUOTAS = "GET_CUOTAS";/* ACCION PARA LA INFORMACION DE LAS CUOTAS */
export const GET_PAGOS = "GET_PAGOS";  /* ACCION PARA VER LOS PAGOS */